openapi: "3.0.1"
info:
  title: "Inventory API"
  version: "1.0.0"
servers:
- url: "https://pgfijup2d5.execute-api.us-east-1.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: "dev"
paths:
  /inventory:
    get:
      responses:
        "200":
          description: "200 response"
          content: {}
      security:
      - CognitoAuthorizer: []
    post:
      responses:
        "200":
          description: "200 response"
          content: {}
      security:
      - CognitoAuthorizer: []
    options:
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
      security:
      - CognitoAuthorizer: []
components:
  securitySchemes:
    CognitoAuthorizer:
      type: "apiKey"
      name: "Authorization"
      in: "header"
      x-amazon-apigateway-authtype: "cognito_user_pools"
